# Generated by Django 4.2.6 on 2023-10-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_course_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
