# Generated by Django 4.2.6 on 2023-10-18 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='userfname',
        ),
        migrations.RemoveField(
            model_name='order',
            name='username',
        ),
    ]
