# Generated by Django 4.2.6 on 2023-10-23 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_order_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['title'], 'verbose_name_plural': 'Работы'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='courseid',
        ),
        migrations.AddField(
            model_name='order',
            name='coursetype',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='shop.course'),
            preserve_default=False,
        ),
    ]
