# Generated by Django 4.2.6 on 2023-12-22 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0010_alter_category_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commenttext', models.TextField()),
                ('parent_id', models.IntegerField(blank=True, null=True)),
                ('coursecom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
