# Generated by Django 4.2.6 on 2023-12-23 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': 'Комментарии'},
        ),
    ]
