# Generated by Django 5.0.1 on 2024-01-19 11:27

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_order_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to=shop.models.product_image_directory),
        ),
    ]
