# Generated by Django 4.2.6 on 2023-12-17 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(choices=[('KFU', 'Казанский Федеральный Университет'), ('KAI', 'Казанский Авиационный Институт'), ('КНИТУ', 'Казанский национальный исследовательский технологический университет'), ('КГЭУ', 'Казанский государственный экономический университет'), ('Другой', 'Нет в списке')], max_length=255)),
                ('agreement_accepted', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
