# Generated by Django 4.2.6 on 2023-12-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0003_alter_profile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='university',
            field=models.CharField(blank=True, choices=[('KFU', 'Казанский Федеральный Университет'), ('KAI', 'Казанский Авиационный Институт'), ('КНИТУ', 'Казанский национальный исследовательский технологический университет'), ('КГЭУ', 'Казанский государственный экономический университет'), ('Другой', 'Нет в списке')], max_length=255),
        ),
    ]
