# Generated by Django 4.2.6 on 2023-12-23 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0004_alter_profile_university'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['slug'], 'verbose_name_plural': 'Профили пользователей'},
        ),
    ]
